import './globals.css';
import { gql } from '@apollo/client';
import { Inter } from 'next/font/google';
import { cookies } from 'next/headers';
import Link from 'next/link';
import { ApolloClientProvider } from '../util/ApolloClientProvider';
import { getClient } from '../util/client';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const fakeSessionToken = cookies().get('fakeSession');

  const { data } = await getClient().query({
    query: gql`
      query LoggedInAnimal($firstName: String!) {
        loggedInAnimalByFirstName(firstName: $firstName) {
          id
          firstName
          type
          accessory
        }
      }
    `,
    variables: {
      firstName: fakeSessionToken?.value || '',
    },
  });

  return (
    <html lang="en">
      <body className={inter.className}>
        <nav
          style={{
            width: '100%',
            backgroundColor: 'lightblue',
            padding: '1rem',
            display: 'flex',
            justifyContent: 'space-between',
          }}
        >
          <div>
            <Link href="/">Home</Link> {''}
            <Link href={{ pathname: '/animals' }}>Animals</Link> {''}
            <Link
              href={{
                pathname: '/animals/admin',
              }}
            >
              Animal admin
            </Link>
          </div>
          <span>{data.loggedInAnimalByFirstName?.firstName}</span>
          {data.loggedInAnimalByFirstName?.firstName ? (
            <Link
              href={{
                pathname: '/logout',
              }}
            >
              Logout
            </Link>
          ) : (
            <Link href={{ pathname: '/login' }}>Login</Link>
          )}
        </nav>
        <ApolloClientProvider>{children}</ApolloClientProvider>

        <br />
        <hr />
        <br />
        <footer>copyright animals4everyone 2023</footer>
      </body>
    </html>
  );
}
